# Generated by Django 2.0.1 on 2018-01-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_auto_20180122_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='tts_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='reg_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='vtu_id',
            field=models.IntegerField(null=True),
        ),
    ]
